// React context for the CFT tokens this browser knows about on the selected
// network, and for the one currently attached: deploy / join, token info, this
// wallet's confidential account, and the token operations. Wraps the
// framework-agnostic `CftClient`.
import { createContext, useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import {
  CftClient,
  CftPrivateState,
  deployCft,
  joinCft,
  type Balances,
  type TokenInfo,
  type TokenParams,
  type TxReceipt,
} from '@midnight-starter/contract';
import { NETWORKS, type NetworkId } from './networks';
import { compiledContract, makeProviders } from './providers';
import { useWallet } from './useWallet';
import { describeError } from './wallet';

/** A token this browser deployed or joined, remembered per network. */
export interface TokenRecord {
  address: string;
  name: string;
  symbol: string;
  decimals: number;
  /** ISO timestamp of the deploy / first join from this browser. */
  addedAt: string;
  /** Account ID that deployed it, when deployed from this browser. */
  deployedBy?: string;
}

export type CftStatus =
  | { kind: 'no-wallet' }
  | { kind: 'detached'; error?: string }
  | { kind: 'attaching'; what: 'deploy' | 'join'; address?: string }
  | {
      kind: 'attached';
      client: CftClient;
      token: TokenInfo;
      balances?: Balances;
      isIssuer: boolean;
      busy?: string;
      error?: string;
    };

export interface CftContextValue {
  status: CftStatus;
  /** Tokens remembered for the connected network, newest first. */
  tokens: TokenRecord[];
  /** Address of the token being attached or attached. */
  selectedAddress?: string;
  /** This browser's CFT identity for the connected wallet (SK / EK live in storage, never shown). */
  accountId?: string;
  deploy: (params: TokenParams) => Promise<void>;
  join: (contractAddress: string) => Promise<void>;
  /** Attach to a remembered token. */
  select: (contractAddress: string) => Promise<void>;
  /** Forget a remembered token (the on-chain token and your identity are untouched). */
  forget: (contractAddress: string) => void;
  /** Detach from the current token without forgetting it. */
  detach: () => void;
  refresh: () => Promise<void>;
  register: () => Promise<TxReceipt | undefined>;
  sweep: () => Promise<TxReceipt | undefined>;
  transfer: (toAccountId: string, amount: bigint) => Promise<TxReceipt | undefined>;
  burn: (amount: bigint) => Promise<TxReceipt | undefined>;
  mint: (toAccountId: string, amount: bigint) => Promise<TxReceipt | undefined>;
  /** Tell the client a spendable balance it cannot derive (verified against the ciphertext). */
  setKnownSpendable: (amount: bigint) => Promise<void>;
  lastReceipt?: TxReceipt;
}

export const CftContext = createContext<CftContextValue | null>(null);

const identityKey = (walletAddress: string) => `midnight-starter:cft-identity:${walletAddress}`;
const tokensKey = (networkId: NetworkId) => `midnight-starter:tokens:${networkId}`;
const selectedKey = (networkId: NetworkId, walletAddress: string) => `midnight-starter:cft-selected:${networkId}:${walletAddress}`;

const readJson = <T,>(key: string): T | undefined => {
  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : undefined;
  } catch {
    return undefined;
  }
};
const writeJson = (key: string, value: unknown) => {
  try {
    if (value === undefined) window.localStorage.removeItem(key);
    else window.localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* storage unavailable */
  }
};

/**
 * CFT accounts are keypairs generated by the dApp, independent of the wallet's
 * own keys. We keep one per wallet address in localStorage so the same wallet
 * always maps to the same confidential account; the private-state store is the
 * source of truth once a contract has been used.
 */
const loadOrCreateIdentity = (walletAddress: string): CftPrivateState => {
  const saved = readJson<{ secretKeyHex: string; encryptionKeyHex: string }>(identityKey(walletAddress));
  if (saved?.secretKeyHex && saved.encryptionKeyHex) return CftPrivateState.fromSecrets(saved.secretKeyHex, saved.encryptionKeyHex);
  const fresh = CftPrivateState.generate();
  writeJson(identityKey(walletAddress), { secretKeyHex: fresh.secretKeyHex, encryptionKeyHex: fresh.encryptionKeyHex });
  return fresh;
};

const loadTokens = (networkId: NetworkId): TokenRecord[] => readJson<TokenRecord[]>(tokensKey(networkId)) ?? [];

/** Joining only reads from the indexer; if it does not answer, say so instead of spinning forever. */
const JOIN_TIMEOUT_MS = 30_000;
const withTimeout = <T,>(promise: Promise<T>, ms: number, message: string): Promise<T> =>
  new Promise<T>((resolve, reject) => {
    const timer = window.setTimeout(() => reject(new Error(message)), ms);
    promise.then(
      (v) => {
        window.clearTimeout(timer);
        resolve(v);
      },
      (e) => {
        window.clearTimeout(timer);
        reject(e);
      },
    );
  });

export function CftProvider({ children }: { children: ReactNode }) {
  const wallet = useWallet();
  const connected = wallet.state.status === 'connected' ? wallet.state : undefined;
  const walletAddress = connected?.address;
  const networkId = connected?.networkId;

  const [status, setStatus] = useState<CftStatus>({ kind: 'no-wallet' });
  const [tokens, setTokens] = useState<TokenRecord[]>([]);
  const [selectedAddress, setSelectedAddress] = useState<string>();
  const [lastReceipt, setLastReceipt] = useState<TxReceipt>();
  const sessionRef = useRef(0);

  const identity = useMemo(() => (walletAddress ? loadOrCreateIdentity(walletAddress) : undefined), [walletAddress]);
  const accountId = identity ? CftPrivateState.accountIdHex(identity) : undefined;

  // The token list follows the network the wallet is on.
  useEffect(() => {
    setTokens(networkId ? loadTokens(networkId) : []);
  }, [networkId]);

  const upsertToken = useCallback(
    (record: TokenRecord) => {
      if (!networkId) return;
      setTokens((prev) => {
        const next = [record, ...prev.filter((t) => t.address !== record.address)];
        writeJson(tokensKey(networkId), next);
        return next;
      });
    },
    [networkId],
  );

  const attach = useCallback(
    async (
      what: 'deploy' | 'join',
      address: string | undefined,
      run: (providers: Awaited<ReturnType<typeof makeProviders>>, id: CftPrivateState) => Promise<CftClient>,
    ) => {
      if (!connected || !identity || !walletAddress) return;
      const session = ++sessionRef.current;
      setSelectedAddress(address);
      setStatus({ kind: 'attaching', what, address });
      try {
        const providers = await makeProviders({
          api: connected.api,
          keys: connected.keys,
          walletAddress,
          network: NETWORKS[connected.networkId],
        });
        const client =
          what === 'join'
            ? await withTimeout(
                run(providers, identity),
                JOIN_TIMEOUT_MS,
                `The indexer for ${NETWORKS[connected.networkId].label} did not answer. Check the network and the contract address.`,
              )
            : await run(providers, identity);
        if (session !== sessionRef.current) return;
        const [token, isIssuer] = await Promise.all([client.token(), client.isIssuer()]);
        if (session !== sessionRef.current) return;
        setSelectedAddress(client.address);
        writeJson(selectedKey(connected.networkId, walletAddress), client.address);
        upsertToken({
          address: client.address,
          name: token.name,
          symbol: token.symbol,
          decimals: token.decimals,
          addedAt: tokens.find((t) => t.address === client.address)?.addedAt ?? new Date().toISOString(),
          deployedBy: what === 'deploy' ? client.accountId : tokens.find((t) => t.address === client.address)?.deployedBy,
        });
        setStatus({ kind: 'attached', client, token, isIssuer });
        // Balances are best-effort and may need the bounded discrete log.
        try {
          const balances = await client.balances();
          if (session !== sessionRef.current) return;
          setStatus((prev) => (prev.kind === 'attached' ? { ...prev, balances } : prev));
        } catch (e) {
          if (session !== sessionRef.current) return;
          setStatus((prev) => (prev.kind === 'attached' ? { ...prev, error: describeError(e) } : prev));
        }
      } catch (e) {
        if (session !== sessionRef.current) return;
        setSelectedAddress(undefined);
        if (walletAddress && connected) writeJson(selectedKey(connected.networkId, walletAddress), undefined);
        setStatus({ kind: 'detached', error: describeError(e) });
      }
    },
    [connected, identity, walletAddress, tokens, upsertToken],
  );

  const join = useCallback(
    (contractAddress: string) =>
      attach('join', contractAddress.trim(), async (providers, id) => {
        const found = await joinCft(providers, compiledContract, contractAddress, id);
        return CftClient.attach(providers, found, id);
      }),
    [attach],
  );

  const deploy = useCallback(
    (params: TokenParams) =>
      attach('deploy', undefined, async (providers, id) => {
        const deployed = await deployCft(providers, compiledContract, id, params);
        return new CftClient(providers, deployed, id);
      }),
    [attach],
  );

  // Keep the latest join() for the reconnect effect without re-running it on every render.
  const joinRef = useRef(join);
  useEffect(() => {
    joinRef.current = join;
  }, [join]);

  // Wallet connected / disconnected / switched network: reset, and re-attach
  // the token remembered for this wallet + network.
  useEffect(() => {
    sessionRef.current++;
    setSelectedAddress(undefined);
    if (!walletAddress || !connected) {
      setStatus({ kind: 'no-wallet' });
      return;
    }
    const remembered = readJson<string>(selectedKey(connected.networkId, walletAddress));
    if (remembered) void joinRef.current(remembered);
    else setStatus({ kind: 'detached' });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [walletAddress, connected?.networkId]);

  const detach = useCallback(() => {
    sessionRef.current++;
    setSelectedAddress(undefined);
    if (walletAddress && connected) writeJson(selectedKey(connected.networkId, walletAddress), undefined);
    setStatus(connected ? { kind: 'detached' } : { kind: 'no-wallet' });
  }, [walletAddress, connected]);

  const forget = useCallback(
    (contractAddress: string) => {
      if (!networkId) return;
      setTokens((prev) => {
        const next = prev.filter((t) => t.address !== contractAddress);
        writeJson(tokensKey(networkId), next);
        return next;
      });
      if (selectedAddress === contractAddress) detach();
    },
    [networkId, selectedAddress, detach],
  );

  const refresh = useCallback(async () => {
    if (status.kind !== 'attached') return;
    const { client } = status;
    const session = sessionRef.current;
    try {
      const [token, isIssuer, balances] = await Promise.all([client.token(), client.isIssuer(), client.balances()]);
      if (session !== sessionRef.current) return;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, token, isIssuer, balances, error: undefined } : prev));
    } catch (e) {
      if (session !== sessionRef.current) return;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, error: describeError(e) } : prev));
    }
  }, [status]);

  /** Run a transaction with busy / error bookkeeping, then refresh. */
  const runTx = useCallback(
    async (label: string, fn: (client: CftClient) => Promise<TxReceipt>): Promise<TxReceipt | undefined> => {
      if (status.kind !== 'attached' || status.busy) return undefined;
      const { client } = status;
      const session = sessionRef.current;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, busy: label, error: undefined } : prev));
      try {
        const r = await fn(client);
        if (session !== sessionRef.current) return r;
        setLastReceipt(r);
        const [token, balances] = await Promise.all([client.token(), client.balances()]);
        if (session !== sessionRef.current) return r;
        setStatus((prev) => (prev.kind === 'attached' ? { ...prev, token, balances, busy: undefined } : prev));
        return r;
      } catch (e) {
        if (session !== sessionRef.current) return undefined;
        setStatus((prev) => (prev.kind === 'attached' ? { ...prev, busy: undefined, error: describeError(e) } : prev));
        return undefined;
      }
    },
    [status],
  );

  const value = useMemo<CftContextValue>(
    () => ({
      status,
      tokens,
      selectedAddress,
      accountId,
      deploy,
      join,
      select: join,
      forget,
      detach,
      refresh,
      register: () => runTx('Registering…', (c) => c.register()),
      sweep: () => runTx('Sweeping…', (c) => c.sweep()),
      transfer: (to, amount) => runTx('Sending…', (c) => c.transfer(to, amount)),
      burn: (amount) => runTx('Burning…', (c) => c.burn(amount)),
      mint: (to, amount) => runTx('Issuing…', (c) => c.mint(to, amount)),
      setKnownSpendable: async (amount) => {
        if (status.kind !== 'attached') return;
        await status.client.setKnownSpendable(amount);
        await refresh();
      },
      lastReceipt,
    }),
    [status, tokens, selectedAddress, accountId, deploy, join, forget, detach, refresh, runTx, lastReceipt],
  );

  return <CftContext.Provider value={value}>{children}</CftContext.Provider>;
}
