// React context for one CFT contract per connected wallet + network:
// deploy / join, token info, this wallet's confidential account, and the
// token operations. Wraps the framework-agnostic `CftClient`.
import { createContext, useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import {
  CftClient,
  CftPrivateState,
  deployCft,
  joinCft,
  type Balances,
  type TokenInfo,
  type TokenParams,
  type TxReceipt,
} from '@midnight-starter/contract';
import { NETWORKS } from './networks';
import { compiledContract, makeProviders } from './providers';
import { useWallet } from './useWallet';
import { describeError } from './wallet';

export type CftStatus =
  | { kind: 'no-wallet' }
  | { kind: 'detached'; error?: string }
  | { kind: 'attaching'; what: 'deploy' | 'join' }
  | { kind: 'attached'; client: CftClient; token: TokenInfo; balances?: Balances; isIssuer: boolean; busy?: string; error?: string };

export interface CftContextValue {
  status: CftStatus;
  /** This browser's CFT identity for the connected wallet (SK / EK live in storage, never shown). */
  accountId?: string;
  deploy: (params: TokenParams) => Promise<void>;
  join: (contractAddress: string) => Promise<void>;
  /** Forget the attached contract address for this network (identity is kept). */
  detach: () => void;
  refresh: () => Promise<void>;
  register: () => Promise<TxReceipt | undefined>;
  sweep: () => Promise<TxReceipt | undefined>;
  transfer: (toAccountId: string, amount: bigint) => Promise<TxReceipt | undefined>;
  burn: (amount: bigint) => Promise<TxReceipt | undefined>;
  mint: (toAccountId: string, amount: bigint) => Promise<TxReceipt | undefined>;
  /** Tell the client a spendable balance it cannot derive (verified against the ciphertext). */
  setKnownSpendable: (amount: bigint) => Promise<void>;
  lastReceipt?: TxReceipt;
}

export const CftContext = createContext<CftContextValue | null>(null);

const identityKey = (walletAddress: string) => `midnight-starter:cft-identity:${walletAddress}`;
const addressKey = (networkId: string, walletAddress: string) => `midnight-starter:cft-address:${networkId}:${walletAddress}`;

const readJson = <T,>(key: string): T | undefined => {
  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : undefined;
  } catch {
    return undefined;
  }
};
const writeJson = (key: string, value: unknown) => {
  try {
    if (value === undefined) window.localStorage.removeItem(key);
    else window.localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* storage unavailable */
  }
};

/**
 * CFT accounts are keypairs generated by the dApp, independent of the wallet's
 * own keys. We keep one per wallet address in localStorage so the same wallet
 * always maps to the same confidential account; the private-state store is the
 * source of truth once a contract has been used.
 */
const loadOrCreateIdentity = (walletAddress: string): CftPrivateState => {
  const saved = readJson<{ secretKeyHex: string; encryptionKeyHex: string }>(identityKey(walletAddress));
  if (saved?.secretKeyHex && saved.encryptionKeyHex) return CftPrivateState.fromSecrets(saved.secretKeyHex, saved.encryptionKeyHex);
  const fresh = CftPrivateState.generate();
  writeJson(identityKey(walletAddress), { secretKeyHex: fresh.secretKeyHex, encryptionKeyHex: fresh.encryptionKeyHex });
  return fresh;
};

export function CftProvider({ children }: { children: ReactNode }) {
  const wallet = useWallet();
  const connected = wallet.state.status === 'connected' ? wallet.state : undefined;
  const walletAddress = connected?.address;
  const networkId = connected?.networkId;

  const [status, setStatus] = useState<CftStatus>({ kind: 'no-wallet' });
  const [lastReceipt, setLastReceipt] = useState<TxReceipt>();
  const sessionRef = useRef(0);

  const identity = useMemo(() => (walletAddress ? loadOrCreateIdentity(walletAddress) : undefined), [walletAddress]);

  const attach = useCallback(
    async (what: 'deploy' | 'join', run: (providers: Awaited<ReturnType<typeof makeProviders>>, id: CftPrivateState) => Promise<CftClient>) => {
      if (!connected || !identity || !walletAddress || !networkId) return;
      const session = ++sessionRef.current;
      setStatus({ kind: 'attaching', what });
      try {
        const providers = await makeProviders({
          api: connected.api,
          keys: connected.keys,
          walletAddress,
          network: NETWORKS[networkId],
        });
        const client = await run(providers, identity);
        if (session !== sessionRef.current) return;
        writeJson(addressKey(networkId, walletAddress), client.address);
        const [token, isIssuer] = await Promise.all([client.token(), client.isIssuer()]);
        if (session !== sessionRef.current) return;
        setStatus({ kind: 'attached', client, token, isIssuer });
        // Balances are best-effort and may need the bounded discrete log.
        try {
          const balances = await client.balances();
          if (session !== sessionRef.current) return;
          setStatus((prev) => (prev.kind === 'attached' ? { ...prev, balances } : prev));
        } catch (e) {
          if (session !== sessionRef.current) return;
          setStatus((prev) => (prev.kind === 'attached' ? { ...prev, error: describeError(e) } : prev));
        }
      } catch (e) {
        if (session !== sessionRef.current) return;
        setStatus({ kind: 'detached', error: describeError(e) });
      }
    },
    [connected, identity, walletAddress, networkId],
  );

  const join = useCallback(
    (contractAddress: string) =>
      attach('join', async (providers, id) => {
        const found = await joinCft(providers, compiledContract, contractAddress, id);
        return CftClient.attach(providers, found, id);
      }),
    [attach],
  );

  const deploy = useCallback(
    (params: TokenParams) =>
      attach('deploy', async (providers, id) => {
        const deployed = await deployCft(providers, compiledContract, id, params);
        return new CftClient(providers, deployed, id);
      }),
    [attach],
  );

  // Wallet connected / disconnected / switched network: reset, and auto-join the
  // address remembered for this wallet + network.
  useEffect(() => {
    sessionRef.current++;
    if (!walletAddress || !networkId) {
      setStatus({ kind: 'no-wallet' });
      return;
    }
    const remembered = readJson<string>(addressKey(networkId, walletAddress));
    if (remembered) void join(remembered);
    else setStatus({ kind: 'detached' });
  }, [walletAddress, networkId, join]);

  const detach = useCallback(() => {
    sessionRef.current++;
    if (walletAddress && networkId) writeJson(addressKey(networkId, walletAddress), undefined);
    setStatus({ kind: 'detached' });
  }, [walletAddress, networkId]);

  const refresh = useCallback(async () => {
    if (status.kind !== 'attached') return;
    const { client } = status;
    const session = sessionRef.current;
    try {
      const [token, isIssuer, balances] = await Promise.all([client.token(), client.isIssuer(), client.balances()]);
      if (session !== sessionRef.current) return;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, token, isIssuer, balances, error: undefined } : prev));
    } catch (e) {
      if (session !== sessionRef.current) return;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, error: describeError(e) } : prev));
    }
  }, [status]);

  /** Run a transaction with busy / error bookkeeping, then refresh. */
  const runTx = useCallback(
    async (label: string, fn: (client: CftClient) => Promise<TxReceipt>): Promise<TxReceipt | undefined> => {
      if (status.kind !== 'attached' || status.busy) return undefined;
      const { client } = status;
      const session = sessionRef.current;
      setStatus((prev) => (prev.kind === 'attached' ? { ...prev, busy: label, error: undefined } : prev));
      try {
        const r = await fn(client);
        if (session !== sessionRef.current) return r;
        setLastReceipt(r);
        const [token, balances] = await Promise.all([client.token(), client.balances()]);
        if (session !== sessionRef.current) return r;
        setStatus((prev) => (prev.kind === 'attached' ? { ...prev, token, balances, busy: undefined } : prev));
        return r;
      } catch (e) {
        if (session !== sessionRef.current) return undefined;
        setStatus((prev) => (prev.kind === 'attached' ? { ...prev, busy: undefined, error: describeError(e) } : prev));
        return undefined;
      }
    },
    [status],
  );

  const value = useMemo<CftContextValue>(
    () => ({
      status,
      accountId: identity ? CftPrivateState.accountIdHex(identity) : undefined,
      deploy,
      join,
      detach,
      refresh,
      register: () => runTx('Registering…', (c) => c.register()),
      sweep: () => runTx('Sweeping…', (c) => c.sweep()),
      transfer: (to, amount) => runTx('Transferring…', (c) => c.transfer(to, amount)),
      burn: (amount) => runTx('Burning…', (c) => c.burn(amount)),
      mint: (to, amount) => runTx('Minting…', (c) => c.mint(to, amount)),
      setKnownSpendable: async (amount) => {
        if (status.kind !== 'attached') return;
        await status.client.setKnownSpendable(amount);
        await refresh();
      },
      lastReceipt,
    }),
    [status, identity, deploy, join, detach, refresh, runTx, lastReceipt],
  );

  return <CftContext.Provider value={value}>{children}</CftContext.Provider>;
}
